/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testkasir3;

import static java.awt.event.KeyEvent.VK_BACK_SPACE;
import java.util.Vector;
import static javafx.beans.binding.Bindings.select;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author : Valerio Meileakhi
 * @Kelas  : Teknik Informatika - 4A
 * NIM     : 2007411012
 */
public class Kasir extends javax.swing.JFrame {

    /**
     * Creates new form Kasir
     */
    public Kasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMarketBigSales = new javax.swing.JPanel();
        LblMarketBigSales = new javax.swing.JLabel();
        LblNamaBarang = new javax.swing.JLabel();
        LblJumlahBarang = new javax.swing.JLabel();
        LblHargaBarang = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Harga = new javax.swing.JTextField();
        Qty = new javax.swing.JTextField();
        BtnTambah = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableKasir = new javax.swing.JTable();
        LblKembalian = new javax.swing.JLabel();
        LblTotalHarga = new javax.swing.JLabel();
        Totalharga = new javax.swing.JLabel();
        Kembalian = new javax.swing.JLabel();
        TxtJumlahUangPembeli = new javax.swing.JTextField();
        BtnBayar = new javax.swing.JButton();
        Pesan = new javax.swing.JLabel();
        Jumlah = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasir");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);

        PanelMarketBigSales.setBackground(new java.awt.Color(153, 255, 153));

        LblMarketBigSales.setBackground(new java.awt.Color(255, 51, 51));
        LblMarketBigSales.setFont(new java.awt.Font("Trajan Pro 3", 3, 18)); // NOI18N
        LblMarketBigSales.setForeground(new java.awt.Color(255, 0, 0));
        LblMarketBigSales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblMarketBigSales.setText("Market BigSales");
        LblMarketBigSales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblNamaBarang.setBackground(new java.awt.Color(102, 255, 204));
        LblNamaBarang.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        LblNamaBarang.setForeground(new java.awt.Color(51, 0, 51));
        LblNamaBarang.setText("Nama Barang   :");

        LblJumlahBarang.setBackground(new java.awt.Color(255, 255, 153));
        LblJumlahBarang.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        LblJumlahBarang.setForeground(new java.awt.Color(51, 0, 51));
        LblJumlahBarang.setText("Jumlah Barang  :");

        LblHargaBarang.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        LblHargaBarang.setForeground(new java.awt.Color(51, 0, 51));
        LblHargaBarang.setText("Harga Barang   :");

        Nama.setBackground(new java.awt.Color(255, 255, 153));
        Nama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });

        Harga.setBackground(new java.awt.Color(255, 255, 153));
        Harga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaActionPerformed(evt);
            }
        });
        Harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HargaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HargaKeyTyped(evt);
            }
        });

        Qty.setBackground(new java.awt.Color(255, 255, 153));
        Qty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QtyActionPerformed(evt);
            }
        });
        Qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                QtyKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QtyKeyTyped(evt);
            }
        });

        BtnTambah.setBackground(new java.awt.Color(51, 255, 255));
        BtnTambah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnTambah.setText("Tambah");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnHapus.setBackground(new java.awt.Color(51, 255, 255));
        BtnHapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        TableKasir.setBackground(new java.awt.Color(204, 204, 204));
        TableKasir.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), java.awt.Color.gray));
        TableKasir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TableKasir.setForeground(new java.awt.Color(255, 204, 255));
        TableKasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Harga Barang", "Jumlah Barang", "Jumlah Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableKasir.setAutoscrolls(false);
        TableKasir.setColumnSelectionAllowed(true);
        TableKasir.setGridColor(new java.awt.Color(255, 255, 255));
        TableKasir.setOpaque(false);
        TableKasir.setSelectionBackground(new java.awt.Color(255, 204, 255));
        jScrollPane1.setViewportView(TableKasir);
        TableKasir.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        LblKembalian.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LblKembalian.setForeground(new java.awt.Color(51, 0, 51));
        LblKembalian.setText("Kembalian           :");

        LblTotalHarga.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LblTotalHarga.setForeground(new java.awt.Color(51, 0, 51));
        LblTotalHarga.setText("Total Harga          :");

        Totalharga.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Totalharga.setForeground(new java.awt.Color(51, 0, 51));
        Totalharga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Totalharga.setText("Rp.0");

        Kembalian.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Kembalian.setForeground(new java.awt.Color(51, 0, 51));
        Kembalian.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Kembalian.setText("Rp.0");

        TxtJumlahUangPembeli.setBackground(new java.awt.Color(255, 255, 204));
        TxtJumlahUangPembeli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtJumlahUangPembeli.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtJumlahUangPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtJumlahUangPembeliActionPerformed(evt);
            }
        });
        TxtJumlahUangPembeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtJumlahUangPembeliKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtJumlahUangPembeliKeyTyped(evt);
            }
        });

        BtnBayar.setBackground(new java.awt.Color(255, 255, 204));
        BtnBayar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnBayar.setText("Bayar");
        BtnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBayarActionPerformed(evt);
            }
        });

        Pesan.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        Pesan.setForeground(new java.awt.Color(204, 0, 0));
        Pesan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelMarketBigSalesLayout = new javax.swing.GroupLayout(PanelMarketBigSales);
        PanelMarketBigSales.setLayout(PanelMarketBigSalesLayout);
        PanelMarketBigSalesLayout.setHorizontalGroup(
            PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMarketBigSalesLayout.createSequentialGroup()
                .addComponent(LblMarketBigSales, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelMarketBigSalesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMarketBigSalesLayout.createSequentialGroup()
                        .addComponent(LblJumlahBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(299, 299, 299))
                    .addGroup(PanelMarketBigSalesLayout.createSequentialGroup()
                        .addGroup(PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LblNamaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblHargaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jumlah)
                        .addGap(234, 234, 234))
                    .addGroup(PanelMarketBigSalesLayout.createSequentialGroup()
                        .addGroup(PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelMarketBigSalesLayout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addGroup(PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMarketBigSalesLayout.createSequentialGroup()
                                    .addGroup(PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LblKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LblTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Kembalian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Totalharga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(48, 48, 48)
                                    .addGroup(PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TxtJumlahUangPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BtnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane1)
                                .addComponent(Pesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelMarketBigSalesLayout.setVerticalGroup(
            PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMarketBigSalesLayout.createSequentialGroup()
                .addComponent(LblMarketBigSales, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMarketBigSalesLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(LblNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMarketBigSalesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Jumlah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Totalharga)
                        .addComponent(LblTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TxtJumlahUangPembeli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelMarketBigSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kembalian)
                    .addComponent(BtnBayar))
                .addGap(33, 33, 33)
                .addComponent(Pesan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMarketBigSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelMarketBigSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(0, 0, 766, 744);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaActionPerformed

    private void QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QtyActionPerformed

    private void TxtJumlahUangPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtJumlahUangPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtJumlahUangPembeliActionPerformed

    private void BtnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBayarActionPerformed
        // TODO add your handling code here:
        int g = Integer.parseInt(Totalharga.getText().substring(3));
        int f = Integer.parseInt(TxtJumlahUangPembeli.getText());
        int h = f - g;
        Kembalian.setText("Rp."+h);
    }//GEN-LAST:event_BtnBayarActionPerformed

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        // TODO add your handling code here:
        Pesan.setText("");
        DefaultTableModel a = (DefaultTableModel) TableKasir.getModel();
        if(Nama.getText().trim().equals("")){
            Pesan.setText("Maaf Kolom Isian Nama Barang Untuk Diisi Terlebih Dahulu");
        }else{
            int c = Integer.parseInt(Harga.getText());
            int b = Integer.parseInt(Qty.getText());
            int d = b * c;
            Jumlah.setText(""+d);
            Jumlah.setVisible(false);
            int t = 0;
            Vector z = new Vector();
            z.add(Nama.getText());
            z.add("Rp.".concat(Harga.getText()));
            z.add(Qty.getText());
            z.add("Rp.".concat(Jumlah.getText()));
            a.addRow(z);
            for(int e = 0; e <a.getRowCount(); e++){
                t += Integer.parseInt(a.getValueAt(e, 3).toString().substring(3));
            }
            Totalharga.setText("Rp."+t);
            Nama.setText("");
            Harga.setText("");
            Qty.setText("");
        }
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void HargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HargaKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HargaKeyPressed

    private void QtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QtyKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_QtyKeyPressed

    private void TxtJumlahUangPembeliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtJumlahUangPembeliKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtJumlahUangPembeliKeyPressed

    private void HargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HargaKeyTyped
        // TODO add your handling code here:
        Pesan.setText("");
        char a = evt.getKeyChar();
        int  b = evt.getKeyCode() ;
        if(!Character.isDigit(a)){
            evt.consume();
            Pesan.setText("Maaf Kolom Isian Nama Barang Untuk Diisi Terlebih Dahulu");
        } else if (b == VK_BACK_SPACE) {
            evt.consume();
            Pesan.setText("Maaf Kolom Isian Nama Barang Untuk Diisi Terlebih Dahulu");
        }
    }//GEN-LAST:event_HargaKeyTyped

    private void QtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QtyKeyTyped
        // TODO add your handling code here:
        Pesan.setText("");
        char a = evt.getKeyChar();
        int  b = evt.getKeyCode() ;
        if(!Character.isDigit(a)){
            evt.consume();
            Pesan.setText("Maaf Kolom Hanya dapat Menginput berupa Angka");
        } else if (b == VK_BACK_SPACE) {
            evt.consume();
            Pesan.setText("Maaf Kolom Hanya dapat Menginput berupa Angka");
        }
    }//GEN-LAST:event_QtyKeyTyped

    private void TxtJumlahUangPembeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtJumlahUangPembeliKeyTyped
        // TODO add your handling code here:
        Pesan.setText("");
        char a = evt.getKeyChar();
        int  b = evt.getKeyCode() ;
        if(!Character.isDigit(a)){
            evt.consume();
            Pesan.setText("Maaf Kolom Hanya dapat Menginput berupa Angka");
        } else if (b == VK_BACK_SPACE) {
            evt.consume();
            Pesan.setText("Maaf Kolom Hanya dapat Menginput berupa Angka");
        }
    }//GEN-LAST:event_TxtJumlahUangPembeliKeyTyped

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel a = (DefaultTableModel) TableKasir.getModel();
        int select = TableKasir.getSelectedRow();
        a.removeRow(select);
        Nama.setText("");
        Harga.setText("");
        Qty.setText("");
        int t= 0;
            for(int e = 0; e <a.getRowCount(); e++){
                t += Integer.parseInt(a.getValueAt(e, 3).toString().substring(3));
            }
        Totalharga.setText("Rp."+t);
        int g = Integer.parseInt(Totalharga.getText().substring(3));
        int f = Integer.parseInt(TxtJumlahUangPembeli.getText());
        int h = f - g;
        Kembalian.setText("Rp."+h);
    }//GEN-LAST:event_BtnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Kasir().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBayar;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JTextField Harga;
    private javax.swing.JLabel Jumlah;
    private javax.swing.JLabel Kembalian;
    private javax.swing.JLabel LblHargaBarang;
    private javax.swing.JLabel LblJumlahBarang;
    private javax.swing.JLabel LblKembalian;
    private javax.swing.JLabel LblMarketBigSales;
    private javax.swing.JLabel LblNamaBarang;
    private javax.swing.JLabel LblTotalHarga;
    private javax.swing.JTextField Nama;
    private javax.swing.JPanel PanelMarketBigSales;
    private javax.swing.JLabel Pesan;
    private javax.swing.JTextField Qty;
    private javax.swing.JTable TableKasir;
    private javax.swing.JLabel Totalharga;
    private javax.swing.JTextField TxtJumlahUangPembeli;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    void isVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
